# Generated by Django 3.0.6 on 2020-05-21 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'Apps',
            },
        ),
        migrations.CreateModel(
            name='Dyno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('app_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynos.App')),
            ],
            options={
                'verbose_name': 'Dyno',
                'verbose_name_plural': 'Dynos',
                'unique_together': {('app_fk', 'name')},
            },
        ),
    ]
