# Generated by Django 3.0.6 on 2020-05-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyno',
            name='cnt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
