# Generated by Django 3.0.6 on 2020-05-22 13:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=5)),
                ('source', models.CharField(blank=True, max_length=64, null=True)),
                ('time_stamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('app_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynos.App')),
                ('dyno_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynos.Dyno')),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
            },
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['-time_stamp'], name='logs_errorl_time_st_57427d_idx'),
        ),
    ]
