# Generated by Django 3.0.6 on 2020-05-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herror',
            name='log_dyno',
            field=models.CharField(default='router', max_length=40),
        ),
        migrations.AddField(
            model_name='herror',
            name='log_source',
            field=models.CharField(choices=[('heroku', 'heroku'), ('app', 'app')], default='heroku', max_length=40),
        ),
        migrations.AddField(
            model_name='rerror',
            name='log_dyno',
            field=models.CharField(default='router', max_length=40),
        ),
        migrations.AddField(
            model_name='rerror',
            name='log_source',
            field=models.CharField(choices=[('heroku', 'heroku'), ('app', 'app')], default='heroku', max_length=40),
        ),
    ]
