# Generated by Django 3.0.6 on 2020-05-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_auto_20200522_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herror',
            name='category',
            field=models.CharField(choices=[('H10', 'H10'), ('H12', 'H12'), ('H14', 'H14'), ('H80', 'H80'), ('H99', 'H99')], default='H10', max_length=5),
        ),
    ]
