# Generated by Django 3.0.6 on 2020-05-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_auto_20200522_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herror',
            name='action',
            field=models.CharField(choices=[(None, 'no-action'), ('restart-dyno', 'restart-dyno'), ('restart-app', 'restart-app')], default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='rerror',
            name='action',
            field=models.CharField(choices=[(None, 'no-action'), ('restart-dyno', 'restart-dyno'), ('restart-app', 'restart-app')], default=None, max_length=15),
        ),
    ]
